# Generated by Django 5.1.2 on 2024-11-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_tagging_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Tagging Content'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='radarr_tag_id',
            field=models.IntegerField(default=0, null=True, verbose_name='Radarr Tag ID'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sonarr_tag_id',
            field=models.IntegerField(default=0, null=True, verbose_name='Sonarr Tag ID'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tag_label',
            field=models.CharField(default='DF', max_length=16, null=True, verbose_name='Tag Label'),
        ),
    ]
