# Generated by Django 4.2.4 on 2023-08-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
