# Generated by Django 4.2.4 on 2023-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_servers',
            field=models.ManyToManyField(blank=True, related_name='users', to='DiscoFlixClient.discordserver'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='users', to='DiscoFlixClient.mediarequest'),
        ),
    ]
