# Generated by Django 4.2.4 on 2023-08-28 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0002_alter_user_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
