# Generated by Django 5.1.2 on 2024-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0003_configuration_openai_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_openai_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable OpenAI Chatbot'),
        ),
    ]
