# Generated by Django 5.1.2 on 2024-12-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0005_configuration_is_mention_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='openai_model_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=255, null=True, verbose_name='OpenAI Model Name'),
        ),
    ]
