# Generated by Django 5.1.2 on 2024-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0006_configuration_openai_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_login_required',
            field=models.BooleanField(default=False, verbose_name='Enable/Require User Login For WebUI'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_verbose_logging',
            field=models.BooleanField(default=False, verbose_name='Verbose Logging In Console'),
        ),
    ]
