# Generated by Django 5.1.2 on 2025-01-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoFlixClient', '0008_configuration_is_request_existing_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_request_existing',
            new_name='is_request_existing_enabled',
        ),
    ]
