# DISCOFLIX COMPOSE EXAMPLE

services:
  discoflix:
    image: nickheyer/discoflix:latest
    container_name: discoflix
    restart: unless-stopped
    init: true
    ports:
      - "5001:5001"
    # env_file: .env
    environment:
      - PORT=5001
    volumes:
      - discoflix_data:/data

volumes:
  discoflix_data:
